// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: internal/proto/order.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Описание заказа
type PizzaOrderRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	CustomerId  int32                  `protobuf:"varint,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	PizzaName   string                 `protobuf:"bytes,2,opt,name=pizza_name,json=pizzaName,proto3" json:"pizza_name,omitempty"`
	Ingredients []string               `protobuf:"bytes,3,rep,name=ingredients,proto3" json:"ingredients,omitempty"`
	Extras      []string               `protobuf:"bytes,4,rep,name=extras,proto3" json:"extras,omitempty"`
	Quantity    int32                  `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	// Данные клиента
	CustomerFirstName string `protobuf:"bytes,6,opt,name=customer_first_name,json=customerFirstName,proto3" json:"customer_first_name,omitempty"` // Имя клиента
	CustomerLastName  string `protobuf:"bytes,7,opt,name=customer_last_name,json=customerLastName,proto3" json:"customer_last_name,omitempty"`    // Фамилия клиента
	CustomerPhone     string `protobuf:"bytes,8,opt,name=customer_phone,json=customerPhone,proto3" json:"customer_phone,omitempty"`               // Номер телефона
	DeliveryAddress   string `protobuf:"bytes,9,opt,name=delivery_address,json=deliveryAddress,proto3" json:"delivery_address,omitempty"`         // Адрес доставки
	IsPickup          bool   `protobuf:"varint,10,opt,name=is_pickup,json=isPickup,proto3" json:"is_pickup,omitempty"`                            // Самовывоз
	PickupLocationId  string `protobuf:"bytes,11,opt,name=pickup_location_id,json=pickupLocationId,proto3" json:"pickup_location_id,omitempty"`   // ID филиала для самовывоза
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PizzaOrderRequest) Reset() {
	*x = PizzaOrderRequest{}
	mi := &file_internal_proto_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PizzaOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PizzaOrderRequest) ProtoMessage() {}

func (x *PizzaOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PizzaOrderRequest.ProtoReflect.Descriptor instead.
func (*PizzaOrderRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_order_proto_rawDescGZIP(), []int{0}
}

func (x *PizzaOrderRequest) GetCustomerId() int32 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *PizzaOrderRequest) GetPizzaName() string {
	if x != nil {
		return x.PizzaName
	}
	return ""
}

func (x *PizzaOrderRequest) GetIngredients() []string {
	if x != nil {
		return x.Ingredients
	}
	return nil
}

func (x *PizzaOrderRequest) GetExtras() []string {
	if x != nil {
		return x.Extras
	}
	return nil
}

func (x *PizzaOrderRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *PizzaOrderRequest) GetCustomerFirstName() string {
	if x != nil {
		return x.CustomerFirstName
	}
	return ""
}

func (x *PizzaOrderRequest) GetCustomerLastName() string {
	if x != nil {
		return x.CustomerLastName
	}
	return ""
}

func (x *PizzaOrderRequest) GetCustomerPhone() string {
	if x != nil {
		return x.CustomerPhone
	}
	return ""
}

func (x *PizzaOrderRequest) GetDeliveryAddress() string {
	if x != nil {
		return x.DeliveryAddress
	}
	return ""
}

func (x *PizzaOrderRequest) GetIsPickup() bool {
	if x != nil {
		return x.IsPickup
	}
	return false
}

func (x *PizzaOrderRequest) GetPickupLocationId() string {
	if x != nil {
		return x.PickupLocationId
	}
	return ""
}

// Ответ сервера
type OrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	DisplayId     string                 `protobuf:"bytes,2,opt,name=display_id,json=displayId,proto3" json:"display_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderResponse) Reset() {
	*x = OrderResponse{}
	mi := &file_internal_proto_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderResponse) ProtoMessage() {}

func (x *OrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderResponse.ProtoReflect.Descriptor instead.
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_order_proto_rawDescGZIP(), []int{1}
}

func (x *OrderResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderResponse) GetDisplayId() string {
	if x != nil {
		return x.DisplayId
	}
	return ""
}

func (x *OrderResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Полный заказ для хранения в Redis (Protobuf формат)
type PizzaOrder struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayId    string                 `protobuf:"bytes,2,opt,name=display_id,json=displayId,proto3" json:"display_id,omitempty"`
	CustomerId   int32                  `protobuf:"varint,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Items        []*PizzaItem           `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	IsSet        bool                   `protobuf:"varint,5,opt,name=is_set,json=isSet,proto3" json:"is_set,omitempty"`
	SetName      string                 `protobuf:"bytes,6,opt,name=set_name,json=setName,proto3" json:"set_name,omitempty"`
	TotalPrice   int32                  `protobuf:"varint,7,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	CreatedAt    int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Unix timestamp в наносекундах
	Status       string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	TargetSlotId string                 `protobuf:"bytes,15,opt,name=target_slot_id,json=targetSlotId,proto3" json:"target_slot_id,omitempty"` // ID временного слота (Capacity-Based Slot Scheduling)
	VisibleAt    string                 `protobuf:"bytes,16,opt,name=visible_at,json=visibleAt,proto3" json:"visible_at,omitempty"`            // RFC3339 - время, когда заказ должен появиться на планшете повара
	// Данные клиента
	CustomerFirstName string `protobuf:"bytes,17,opt,name=customer_first_name,json=customerFirstName,proto3" json:"customer_first_name,omitempty"` // Имя клиента
	CustomerLastName  string `protobuf:"bytes,18,opt,name=customer_last_name,json=customerLastName,proto3" json:"customer_last_name,omitempty"`    // Фамилия клиента
	CustomerPhone     string `protobuf:"bytes,19,opt,name=customer_phone,json=customerPhone,proto3" json:"customer_phone,omitempty"`               // Номер телефона
	DeliveryAddress   string `protobuf:"bytes,20,opt,name=delivery_address,json=deliveryAddress,proto3" json:"delivery_address,omitempty"`         // Адрес доставки
	IsPickup          bool   `protobuf:"varint,21,opt,name=is_pickup,json=isPickup,proto3" json:"is_pickup,omitempty"`                             // Самовывоз
	PickupLocationId  string `protobuf:"bytes,22,opt,name=pickup_location_id,json=pickupLocationId,proto3" json:"pickup_location_id,omitempty"`    // ID филиала для самовывоза
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PizzaOrder) Reset() {
	*x = PizzaOrder{}
	mi := &file_internal_proto_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PizzaOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PizzaOrder) ProtoMessage() {}

func (x *PizzaOrder) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PizzaOrder.ProtoReflect.Descriptor instead.
func (*PizzaOrder) Descriptor() ([]byte, []int) {
	return file_internal_proto_order_proto_rawDescGZIP(), []int{2}
}

func (x *PizzaOrder) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PizzaOrder) GetDisplayId() string {
	if x != nil {
		return x.DisplayId
	}
	return ""
}

func (x *PizzaOrder) GetCustomerId() int32 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *PizzaOrder) GetItems() []*PizzaItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *PizzaOrder) GetIsSet() bool {
	if x != nil {
		return x.IsSet
	}
	return false
}

func (x *PizzaOrder) GetSetName() string {
	if x != nil {
		return x.SetName
	}
	return ""
}

func (x *PizzaOrder) GetTotalPrice() int32 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *PizzaOrder) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *PizzaOrder) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PizzaOrder) GetTargetSlotId() string {
	if x != nil {
		return x.TargetSlotId
	}
	return ""
}

func (x *PizzaOrder) GetVisibleAt() string {
	if x != nil {
		return x.VisibleAt
	}
	return ""
}

func (x *PizzaOrder) GetCustomerFirstName() string {
	if x != nil {
		return x.CustomerFirstName
	}
	return ""
}

func (x *PizzaOrder) GetCustomerLastName() string {
	if x != nil {
		return x.CustomerLastName
	}
	return ""
}

func (x *PizzaOrder) GetCustomerPhone() string {
	if x != nil {
		return x.CustomerPhone
	}
	return ""
}

func (x *PizzaOrder) GetDeliveryAddress() string {
	if x != nil {
		return x.DeliveryAddress
	}
	return ""
}

func (x *PizzaOrder) GetIsPickup() bool {
	if x != nil {
		return x.IsPickup
	}
	return false
}

func (x *PizzaOrder) GetPickupLocationId() string {
	if x != nil {
		return x.PickupLocationId
	}
	return ""
}

// Элемент заказа
type PizzaItem struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PizzaName         string                 `protobuf:"bytes,1,opt,name=pizza_name,json=pizzaName,proto3" json:"pizza_name,omitempty"`
	Ingredients       []string               `protobuf:"bytes,2,rep,name=ingredients,proto3" json:"ingredients,omitempty"`
	IngredientAmounts map[string]int32       `protobuf:"bytes,6,rep,name=ingredient_amounts,json=ingredientAmounts,proto3" json:"ingredient_amounts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // Дозировка ингредиентов в граммах
	Extras            []string               `protobuf:"bytes,3,rep,name=extras,proto3" json:"extras,omitempty"`
	Quantity          int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price             int32                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	SetName           string                 `protobuf:"bytes,7,opt,name=set_name,json=setName,proto3" json:"set_name,omitempty"`          // Название набора, если это элемент набора
	IsSetItem         bool                   `protobuf:"varint,8,opt,name=is_set_item,json=isSetItem,proto3" json:"is_set_item,omitempty"` // Флаг что это элемент набора
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PizzaItem) Reset() {
	*x = PizzaItem{}
	mi := &file_internal_proto_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PizzaItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PizzaItem) ProtoMessage() {}

func (x *PizzaItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PizzaItem.ProtoReflect.Descriptor instead.
func (*PizzaItem) Descriptor() ([]byte, []int) {
	return file_internal_proto_order_proto_rawDescGZIP(), []int{3}
}

func (x *PizzaItem) GetPizzaName() string {
	if x != nil {
		return x.PizzaName
	}
	return ""
}

func (x *PizzaItem) GetIngredients() []string {
	if x != nil {
		return x.Ingredients
	}
	return nil
}

func (x *PizzaItem) GetIngredientAmounts() map[string]int32 {
	if x != nil {
		return x.IngredientAmounts
	}
	return nil
}

func (x *PizzaItem) GetExtras() []string {
	if x != nil {
		return x.Extras
	}
	return nil
}

func (x *PizzaItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *PizzaItem) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *PizzaItem) GetSetName() string {
	if x != nil {
		return x.SetName
	}
	return ""
}

func (x *PizzaItem) GetIsSetItem() bool {
	if x != nil {
		return x.IsSetItem
	}
	return false
}

var File_internal_proto_order_proto protoreflect.FileDescriptor

const file_internal_proto_order_proto_rawDesc = "" +
	"\n" +
	"\x1ainternal/proto/order.proto\x12\x05order\"\xa4\x03\n" +
	"\x11PizzaOrderRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\x05R\n" +
	"customerId\x12\x1d\n" +
	"\n" +
	"pizza_name\x18\x02 \x01(\tR\tpizzaName\x12 \n" +
	"\vingredients\x18\x03 \x03(\tR\vingredients\x12\x16\n" +
	"\x06extras\x18\x04 \x03(\tR\x06extras\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x05R\bquantity\x12.\n" +
	"\x13customer_first_name\x18\x06 \x01(\tR\x11customerFirstName\x12,\n" +
	"\x12customer_last_name\x18\a \x01(\tR\x10customerLastName\x12%\n" +
	"\x0ecustomer_phone\x18\b \x01(\tR\rcustomerPhone\x12)\n" +
	"\x10delivery_address\x18\t \x01(\tR\x0fdeliveryAddress\x12\x1b\n" +
	"\tis_pickup\x18\n" +
	" \x01(\bR\bisPickup\x12,\n" +
	"\x12pickup_location_id\x18\v \x01(\tR\x10pickupLocationId\"a\n" +
	"\rOrderResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1d\n" +
	"\n" +
	"display_id\x18\x02 \x01(\tR\tdisplayId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\xce\x04\n" +
	"\n" +
	"PizzaOrder\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"display_id\x18\x02 \x01(\tR\tdisplayId\x12\x1f\n" +
	"\vcustomer_id\x18\x03 \x01(\x05R\n" +
	"customerId\x12&\n" +
	"\x05items\x18\x04 \x03(\v2\x10.order.PizzaItemR\x05items\x12\x15\n" +
	"\x06is_set\x18\x05 \x01(\bR\x05isSet\x12\x19\n" +
	"\bset_name\x18\x06 \x01(\tR\asetName\x12\x1f\n" +
	"\vtotal_price\x18\a \x01(\x05R\n" +
	"totalPrice\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12$\n" +
	"\x0etarget_slot_id\x18\x0f \x01(\tR\ftargetSlotId\x12\x1d\n" +
	"\n" +
	"visible_at\x18\x10 \x01(\tR\tvisibleAt\x12.\n" +
	"\x13customer_first_name\x18\x11 \x01(\tR\x11customerFirstName\x12,\n" +
	"\x12customer_last_name\x18\x12 \x01(\tR\x10customerLastName\x12%\n" +
	"\x0ecustomer_phone\x18\x13 \x01(\tR\rcustomerPhone\x12)\n" +
	"\x10delivery_address\x18\x14 \x01(\tR\x0fdeliveryAddress\x12\x1b\n" +
	"\tis_pickup\x18\x15 \x01(\bR\bisPickup\x12,\n" +
	"\x12pickup_location_id\x18\x16 \x01(\tR\x10pickupLocationId\"\xef\x02\n" +
	"\tPizzaItem\x12\x1d\n" +
	"\n" +
	"pizza_name\x18\x01 \x01(\tR\tpizzaName\x12 \n" +
	"\vingredients\x18\x02 \x03(\tR\vingredients\x12V\n" +
	"\x12ingredient_amounts\x18\x06 \x03(\v2'.order.PizzaItem.IngredientAmountsEntryR\x11ingredientAmounts\x12\x16\n" +
	"\x06extras\x18\x03 \x03(\tR\x06extras\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x05R\x05price\x12\x19\n" +
	"\bset_name\x18\a \x01(\tR\asetName\x12\x1e\n" +
	"\vis_set_item\x18\b \x01(\bR\tisSetItem\x1aD\n" +
	"\x16IngredientAmountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x012M\n" +
	"\fOrderService\x12=\n" +
	"\vCreateOrder\x12\x18.order.PizzaOrderRequest\x1a\x14.order.OrderResponseB2\n" +
	"\x15com.erp.kitchen.protoB\n" +
	"OrderProtoZ\r./internal/pbb\x06proto3"

var (
	file_internal_proto_order_proto_rawDescOnce sync.Once
	file_internal_proto_order_proto_rawDescData []byte
)

func file_internal_proto_order_proto_rawDescGZIP() []byte {
	file_internal_proto_order_proto_rawDescOnce.Do(func() {
		file_internal_proto_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_order_proto_rawDesc), len(file_internal_proto_order_proto_rawDesc)))
	})
	return file_internal_proto_order_proto_rawDescData
}

var file_internal_proto_order_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_proto_order_proto_goTypes = []any{
	(*PizzaOrderRequest)(nil), // 0: order.PizzaOrderRequest
	(*OrderResponse)(nil),     // 1: order.OrderResponse
	(*PizzaOrder)(nil),        // 2: order.PizzaOrder
	(*PizzaItem)(nil),         // 3: order.PizzaItem
	nil,                       // 4: order.PizzaItem.IngredientAmountsEntry
}
var file_internal_proto_order_proto_depIdxs = []int32{
	3, // 0: order.PizzaOrder.items:type_name -> order.PizzaItem
	4, // 1: order.PizzaItem.ingredient_amounts:type_name -> order.PizzaItem.IngredientAmountsEntry
	0, // 2: order.OrderService.CreateOrder:input_type -> order.PizzaOrderRequest
	1, // 3: order.OrderService.CreateOrder:output_type -> order.OrderResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_proto_order_proto_init() }
func file_internal_proto_order_proto_init() {
	if File_internal_proto_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_order_proto_rawDesc), len(file_internal_proto_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_order_proto_goTypes,
		DependencyIndexes: file_internal_proto_order_proto_depIdxs,
		MessageInfos:      file_internal_proto_order_proto_msgTypes,
	}.Build()
	File_internal_proto_order_proto = out.File
	file_internal_proto_order_proto_goTypes = nil
	file_internal_proto_order_proto_depIdxs = nil
}
